export type Service = {
  id: string;
  title: string;
  short: string;
  detail: string;
  illustration: 'kids' | 'surgery' | 'mother' | 'heart' | 'lab' | 'ambulance';
};

export const specialties: Service[] = [
  { id: 'general', title: 'General medicine & surgery', short: 'Treatment and surgery for all types of diseases.', detail: 'Our general medicine and surgery team looks after day-to-day illness as well as routine planned procedures. As a focused 15–16 bed hospital, we keep our team small enough to give every patient personal attention, while working alongside senior consultants for complex cases. You can expect a clear diagnosis, an honest plan, and care that puts your comfort first.', illustration: 'surgery' },
  { id: 'laparoscopy', title: 'Laparoscopic surgery', short: 'Gallbladder stones, hernia and piles using keyhole techniques.', detail: 'We use minimally invasive (laparoscopic) surgery for gallbladder stones, hernia and piles. Smaller cuts usually mean less pain, quicker recovery and shorter hospital stays — which is especially valuable in a hospital of our size where every bed matters. Your surgeon will explain the approach, expected recovery time and any alternatives before the procedure.', illustration: 'surgery' },
  { id: 'maternity', title: "Women's health & maternity", short: "Women's health concerns, normal and supported delivery.", detail: "From routine gynaecology check-ups to pregnancy care and delivery, our team supports women through every stage. Because we are a 15–16 bed hospital, mothers get attentive, personalised care in a calm environment, with a paediatric and neonatal team ready to step in if the baby needs extra support right after birth.", illustration: 'mother' },
  { id: 'neonatal', title: 'Child & neonatal care (NICU)', short: "Children's surgery and a dedicated NICU for newborns.", detail: "Our NICU is equipped to care for premature and newborn babies who need a little extra help, including neonatal ventilation support. We also perform common paediatric laparoscopic procedures. As a smaller hospital, our neonatal team keeps close watch on every baby and keeps parents updated at every step.", illustration: 'kids' },
  { id: 'general-surgery', title: 'General & abdominal surgery', short: 'Hydrocele, appendicitis, abdominal pain and pancreatic stones.', detail: 'We treat common abdominal conditions including hydrocele, appendicitis, abdominal pain and swelling, and pancreatic stones. Most cases are managed with minimally invasive techniques when appropriate, supported by on-site ultrasound and pathology so diagnosis and treatment can move quickly.', illustration: 'surgery' },
  { id: 'uro-ent', title: 'Kidney, piles, breast & ENT', short: 'Kidney stones, piles, hemorrhoids, breast lumps and ENT endoscopy.', detail: 'From kidney stones and piles to breast lumps and common ENT conditions, our team offers diagnosis and treatment under one roof. We use endoscopic techniques for many ENT and urology cases, helping patients recover faster. Every plan is reviewed by a senior consultant before treatment begins.', illustration: 'heart' },
  { id: 'orthopaedics', title: 'Orthopaedics & trauma', short: 'Fracture care with image intensifier (C-arm), bone & spine treatment.', detail: 'Fractures are managed in our operation theatre using a C-arm (image intensifier) so the surgeon can see the bones clearly during the procedure. We also treat bone and spine conditions and provide plaster/cast services. As a 15–16 bed hospital, we focus on accurate fixation, early mobilisation and clear guidance for home recovery.', illustration: 'surgery' },
  { id: 'diagnostics', title: 'Pathology, X-ray, ECG & OPD', short: 'On-site pathology, X-ray, ECG, nebulizer and oxygen support.', detail: 'Our out-patient department works alongside on-site pathology, X-ray and ECG so most tests are done the same day. Nebulizer and oxygen support are available for routine and emergency care, helping our team act quickly when patients arrive with breathing difficulty or other urgent concerns.', illustration: 'lab' },
  { id: 'icu', title: 'ICU, NICU & 24×7 ambulance', short: 'ICU, NICU and round-the-clock ambulance service.', detail: 'Our ICU and NICU are staffed 24×7 by trained doctors and nurses, with monitors, ventilators and emergency medicines ready. The hospital ambulance is also available around the clock for transfers and emergencies. Because we are a focused 15–16 bed hospital, the team that admits you is the same team that looks after you through recovery.', illustration: 'ambulance' },
];